Document: python-leap-client
Title: Debian python-leap-client Manual
Author: <insert document author here>
Abstract: This manual describes what python-leap-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-leap-client/python-leap-client.sgml.gz

Format: postscript
Files: /usr/share/doc/python-leap-client/python-leap-client.ps.gz

Format: text
Files: /usr/share/doc/python-leap-client/python-leap-client.text.gz

Format: HTML
Index: /usr/share/doc/python-leap-client/html/index.html
Files: /usr/share/doc/python-leap-client/html/*.html
