
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.9.1'
version_full = '422f634b654e396fa846c5d17311b9ec7dca2b81'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
