
# This file was generated by the `freeze_debianver` command in setup.py
# Using 'versioneer.py' (0.7+) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.7.0'
version_full = '91379653817a63bb7b30af2d5e1d5d23a76319d9'


def get_versions(default={}, verbose=False):
        return {'version': version_version, 'full': version_full}
