.\" groff -man -Tascii foo.1
.TH LEAP 1 "July 2012" leap "User manual"
.SH NAME
leap \- the internet encryption toolkit
.SH SYNOPSIS
.B leap
.RI [ OPTIONS ]
.SH DESCRIPTION
.B leap
allows to ... blah blah ...
.SH OPTIONS
.IP "-d, --debug"
Show additional information on the command line.
.IP "-h, --help"
Show information about the usage of the command.
.SH FILES
.TP
.I /usr/share/polkit-1/actions/net.openvpn.gui.leap.policy
The PolicyKit definitions of the privileges used by leap, e.g. to run openvpn as root. To change the privileges please have a look at 
.BR PolicyKit.conf (1).
.SH DIAGNOSTICS
By default leaps logs to ... /dev/null. Furthermore you 
can foobarize yourself.
.SH EXTRA TIPS
Trust your technolust!
.SH HOMEPAGE
http://leap.se
.SH BUGS
You can report bugs at the bugtracker site of leap:
http://leap.se/code
.SH AUTHOR
This manpage written by kali <kaliyuga at riseup dot net> for the debian package, but obviously can be used for any other distribution.
.SH SEE ALSO
.BR PolicyKit.conf (7)
